// internal name, relative filename

IMG(tetrion_qs_white, "gfx/tetrion_qs_white")
IMG(tets_bright_qs, "gfx/tets_bright_qs")
IMG(tets_bright_qs_small, "gfx/tets_bright_qs_small")
IMG(tets_dark_qs, "gfx/tets_dark_qs")
IMG(playfield_grid, "gfx/playfield_grid")
IMG(playfield_grid_alt, "gfx/playfield_grid_alt")
IMG(font, "gfx/font")
IMG(font_no_outline, "gfx/font_no_outline")
IMG(font_outline_only, "gfx/font_outline_only")
IMG(font_square_no_outline, "gfx/font_square_no_outline")
IMG(font_square_outline_only, "gfx/font_square_outline_only")
IMG(font_thin, "gfx/font_thin")
IMG(font_thin_no_outline, "gfx/font_thin_no_outline")
IMG(font_thin_outline_only, "gfx/font_thin_outline_only")
IMG(font_small, "gfx/font_small")
IMG(font_tiny, "gfx/font_tiny")
IMG(font_fixedsys_excelsior, "gfx/font_fixedsys_excelsior")
IMG(misc, "gfx/misc")
// the backgrounds must be adjacent and in order because they are addressed by offset:
IMG(bg0, "gfx/bg0")
IMG(bg1, "gfx/bg1")
IMG(bg2, "gfx/bg2")
IMG(bg3, "gfx/bg3")
IMG(bg4, "gfx/bg4")
IMG(bg5, "gfx/bg5")
IMG(bg6, "gfx/bg6")
IMG(bg7, "gfx/bg7")
IMG(bg8, "gfx/bg8")
IMG(bg9, "gfx/bg9")
IMG(bg10, "gfx/bg10")
IMG(bg11, "gfx/bg11")
IMG(bg12, "gfx/bg12")
IMG(bg_temp, "gfx/bg-temp")
IMG(bg_darken, "gfx/bg_darken")
IMG(medals, "gfx/medals")

// the frames must be adjacent and in order because they are addressed by offset:
IMG(animation_lineclear0, "gfx/animation/lineclear0")
IMG(animation_lineclear1, "gfx/animation/lineclear1")
IMG(animation_lineclear2, "gfx/animation/lineclear2")
IMG(animation_lineclear3, "gfx/animation/lineclear3")
IMG(animation_lineclear4, "gfx/animation/lineclear4")

IMG(g1_tetrion_g1, "gfx/g1/tetrion_g1")

//IMG(g2_tets_bright_g2, "gfx/g2/tets_bright_g2")
//IMG(g2_tets_bright_g2_small, "gfx/g2/tets_bright_g2_small")
//IMG(g2_tets_dark_g2, "gfx/g2/tets_dark_g2")
IMG(g2_tetrion_g2_death, "gfx/g2/tetrion_g2_death")
IMG(g2_tetrion_g2_master, "gfx/g2/tetrion_g2_master")

IMG(g3_tetrion_g3_terror, "gfx/g3/tetrion_g3_terror")
